name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v1

    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "./"
        REMOTE_HOST: "54.193.129.176"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/html-docs-hello-world/"
    - run: sudo apt-get update
    - run: sudo apt-get install \
           apt-transport-https \
           ca-certificates \
           curl \
          gnupg-agent \
          software-properties-common
    - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - run: sudo apt-get install docker-ce docker-ce-cli containerd.io
    - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - run: sudo apt-get install docker-ce docker-ce-cli containerd.io
    - run: apt-cache madison docker-ce
    - run: sudo apt-get install docker-ce docker-ce-cli containerd.io
    - run: sudo apt install docker.io
    - run: sudo apt install docker-compose
    - run: pwd
    - run: sudo apt install -y python3-flask
    - run: FLASK_APP=main.py flask run
